-- ============================================================
-- DechBar Analytics System v1.0
-- Migration: analytics_system
--
-- Creates 5 new tables:
--   1. audio_sessions       — one row per StickyPlayer listening session
--   2. audio_events         — granular events within a session
--   3. user_activity_log    — app open events (DAU L1)
--   4. user_activity_streaks — daily streak with grace day logic
--   5. platform_daily_stats — nightly aggregates (cron job)
--
-- RLS admin check: user_roles table (role_id IN ('admin','ceo'))
-- ============================================================

-- ============================================================
-- 1. audio_sessions
-- ============================================================

CREATE TABLE IF NOT EXISTS audio_sessions (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id              UUID NOT NULL UNIQUE,  -- generated by frontend at play_started
  user_id                 UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,

  -- Content hierarchy (Akademie structure)
  lesson_id               TEXT NOT NULL,           -- lesson UUID / track id
  lesson_title            TEXT,                    -- "D1 Zavři záložky"
  series_id               TEXT,                    -- series UUID
  series_title            TEXT,                    -- "Týden 1"
  program_id              TEXT,                    -- program UUID
  program_title           TEXT,                    -- "Digitální ticho"
  category_slug           TEXT,                    -- 'rezim' | 'vyzvy' | 'decharna' | ...
  category_title          TEXT,                    -- "Program REŽIM"

  -- Timing
  started_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at                TIMESTAMPTZ,             -- NULL until session ends

  -- Audio metadata
  audio_duration_seconds  INTEGER,                 -- total track length in seconds

  -- Playback stats (updated periodically + on close)
  unique_listen_seconds   INTEGER NOT NULL DEFAULT 0,   -- unique seconds (merge intervals)
  completion_percent      DECIMAL(5,2) NOT NULL DEFAULT 0, -- max reached % (0-100)
  is_completed            BOOLEAN NOT NULL DEFAULT false,  -- >= 80%
  was_abandoned           BOOLEAN NOT NULL DEFAULT false,  -- closed before 80%
  seek_count              INTEGER NOT NULL DEFAULT 0,
  pause_count             INTEGER NOT NULL DEFAULT 0,

  -- Device / platform
  platform                TEXT,                    -- 'web' | 'ios' | 'android'
  app_version             TEXT,

  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audio_sessions_user
  ON audio_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_audio_sessions_lesson
  ON audio_sessions(lesson_id);
CREATE INDEX IF NOT EXISTS idx_audio_sessions_started
  ON audio_sessions(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_audio_sessions_category
  ON audio_sessions(category_slug);

ALTER TABLE audio_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "audio_sessions_user_manage"
  ON audio_sessions FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "audio_sessions_admin_read"
  ON audio_sessions FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid()
        AND role_id IN ('admin', 'ceo')
    )
  );

-- ============================================================
-- 2. audio_events
-- ============================================================

CREATE TABLE IF NOT EXISTS audio_events (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id        UUID NOT NULL,               -- → audio_sessions.session_id
  user_id           UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  lesson_id         TEXT NOT NULL,

  event_type        TEXT NOT NULL CHECK (event_type IN (
    'play_started',     -- user clicked play (session start)
    'paused',           -- user paused
    'resumed',          -- user resumed
    'seeked',           -- user jumped to different position
    'completed',        -- 80% threshold reached
    'closed',           -- user closed player
    'position_snapshot' -- periodic snapshot every 15s (for drop-off curve)
  )),

  -- Playhead position and progress at event time
  position_seconds  DECIMAL(8,2),
  listen_percent    DECIMAL(5,2),               -- % uniquely listened SO FAR

  -- Only for 'seeked' events
  seek_from_seconds DECIMAL(8,2),
  seek_to_seconds   DECIMAL(8,2),

  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audio_events_session
  ON audio_events(session_id);
CREATE INDEX IF NOT EXISTS idx_audio_events_user
  ON audio_events(user_id);
CREATE INDEX IF NOT EXISTS idx_audio_events_type
  ON audio_events(event_type);
CREATE INDEX IF NOT EXISTS idx_audio_events_created
  ON audio_events(created_at DESC);

ALTER TABLE audio_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "audio_events_user_manage"
  ON audio_events FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "audio_events_admin_read"
  ON audio_events FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid()
        AND role_id IN ('admin', 'ceo')
    )
  );

-- ============================================================
-- 3. user_activity_log
-- ============================================================

CREATE TABLE IF NOT EXISTS user_activity_log (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  event_type  TEXT NOT NULL CHECK (event_type IN ('app_open')),
  platform    TEXT,                              -- 'web' | 'ios' | 'android'
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Partial index for fast DAU query (app_open events only)
CREATE INDEX IF NOT EXISTS idx_activity_log_user_date
  ON user_activity_log(user_id, created_at DESC)
  WHERE event_type = 'app_open';

ALTER TABLE user_activity_log ENABLE ROW LEVEL SECURITY;

-- Users can only insert their own events (no read needed from client)
CREATE POLICY "activity_log_user_insert"
  ON user_activity_log FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "activity_log_admin_read"
  ON user_activity_log FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid()
        AND role_id IN ('admin', 'ceo')
    )
  );

-- ============================================================
-- 4. user_activity_streaks
-- ============================================================

CREATE TABLE IF NOT EXISTS user_activity_streaks (
  user_id               UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  current_streak_days   INTEGER NOT NULL DEFAULT 0,
  longest_streak_days   INTEGER NOT NULL DEFAULT 0,
  last_active_date      DATE,
  grace_day_used        BOOLEAN NOT NULL DEFAULT false,
  -- NOTE for gamification component: replace grace_day_used BOOLEAN
  -- with jokers_remaining INTEGER DEFAULT 3 + jokers_reset_at DATE
  streak_started_at     DATE,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE user_activity_streaks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "streaks_user_manage"
  ON user_activity_streaks FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "streaks_admin_read"
  ON user_activity_streaks FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid()
        AND role_id IN ('admin', 'ceo')
    )
  );

-- ============================================================
-- 5. platform_daily_stats
-- ============================================================

CREATE TABLE IF NOT EXISTS platform_daily_stats (
  stat_date                     DATE PRIMARY KEY,
  dau_l1                        INTEGER NOT NULL DEFAULT 0, -- Level 1: opened app
  dau_l2                        INTEGER NOT NULL DEFAULT 0, -- Level 2: started activity
  dau_l3                        INTEGER NOT NULL DEFAULT 0, -- Level 3: completed activity
  new_registrations             INTEGER NOT NULL DEFAULT 0,
  total_exercise_sessions       INTEGER NOT NULL DEFAULT 0,
  completed_exercise_sessions   INTEGER NOT NULL DEFAULT 0,
  total_audio_sessions          INTEGER NOT NULL DEFAULT 0,
  completed_audio_sessions      INTEGER NOT NULL DEFAULT 0, -- reached 80%
  total_minutes_breathed        DECIMAL(10,2) NOT NULL DEFAULT 0, -- exercise + audio
  exercise_minutes              DECIMAL(10,2) NOT NULL DEFAULT 0,
  audio_minutes                 DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- No RLS on platform_daily_stats — only written by service role (cron job)
-- and read by admin queries via service role or direct Supabase admin access
ALTER TABLE platform_daily_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "platform_stats_admin_read"
  ON platform_daily_stats FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid()
        AND role_id IN ('admin', 'ceo')
    )
  );
